---
# Introduction Numpy
---

![Image](./img/intro_numpy.png)

Numpy est une librairie d'extention à Python pour les tableaux multidimentionnels.
- calcul vectoriel avec représentation multidimentionnelle (ex : vecteur 1D, serie temporelle 2D, IRMAnat 3D, IRM Fonctionnelle 4D)
- efficace en gestion mémoire (proche hardware - gd enssemble de nbres ordonnés)
- conçu pour le calcul scientifique
- "brique" de base pour tout l'ecosystème scientifique (pandas/nipype/mne/scipy/...)

In [1]:
import numpy as np             # convention d'import
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

Opérations numériques rapides :

In [2]:
L = list(range(1000))             # Liste
%timeit [i**2 for i in L]

a = np.arange(1000)         # Numpy array
%timeit a**2

#pouquoi ? numpy est écrit en C !

227 µs ± 11.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
1.15 µs ± 90.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Doc : http://docs.scipy.org/

Aide interractive :

In [3]:
import numpy as np 
#np. + touche 'tab'
np.array?

Docstring:
array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.  This argument can only be used to 'upcast' the array.  For
    downcasting, use the .astype(t) method.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (

In [4]:
np.con*?

np.concatenate
np.conj
np.conjugate
np.convolve

# Multi-dimensions : ndim, shape, size

## 1D

In [5]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [6]:
a.ndim

1

In [7]:
a.shape # 'taille' des dimensions

(4,)

In [8]:
a.size # nbre d'elements total

4

## 2D, 3D, ... ND

In [9]:
b = np.array([[0, 1, 2], [3, 4, 5]])    # 2 x 3 array
print('b : ', b)
print('b.ndim : ', b.ndim)
print('b.shape : ', b.shape)
print('b.size : ', b.size)

# attention à la necessité de dimentions cohérentes 
# b = np.array([[0, 1, 2], [3, 4, 5, 6]]) va pas marcher

b :  [[0 1 2]
 [3 4 5]]
b.ndim :  2
b.shape :  (2, 3)
b.size :  6


In [10]:
c = np.array([
        [[1,2,3], [2,3,4], [3,4,5], [4,5,6]],
        [[2,3,4], [3,4,5], [4,5,6], [5,6,7]],
        [[3,4,5], [4,5,6], [5,6,7], [6,7,8]],
        [[4,5,6], [5,6,7], [6,7,8], [7,8,9]],
        [[5,6,7], [6,7,8], [7,8,9], [8,9,10]]
    ])
print('c.ndim : ', c.ndim)
print('c.shape : ', c.shape)
print('c.size : ', c.size)

c.ndim :  3
c.shape :  (5, 4, 3)
c.size :  60


<img src="./img/sequence4_array_dims.png">

# Fonctions

En pratique, on entre rarement les nombres à la main...

### Eléments réguliairement espacés :

In [11]:
a = np.arange(10) # 0 .. n-1  (!)
a

#equivalent du range mais en numpy array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
b = np.arange(1, 9, 2) # début, fin (exclusive), pas
b

array([1, 3, 5, 7])

### Ou espacés en donnant le nombre de points :

In [13]:
c = np.linspace(0, 1, 6)   # début, fin, nombre de points
c

# attention, ici c'est inclus !

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [14]:
d = np.linspace(0, 1, 5, endpoint=False)
d

#(intro mot clef)

array([0. , 0.2, 0.4, 0.6, 0.8])

### Tableaux usuels :

In [15]:
a = np.ones((3, 3))  # np.ones((3, 3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
b = np.zeros((2, 4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
c = np.random.rand(10)      # distribution uniforme entre [0, 1]
c

array([0.40284047, 0.97955698, 0.89577927, 0.41977505, 0.30317348,
       0.8943219 , 0.15795278, 0.16387659, 0.32275458, 0.47181216])

In [18]:
d = np.random.randn(4)      # distribution gaussian de moy 0 et stdv 1
d

array([-0.12329483,  0.70351043, -1.04029892, -1.04342994])

In [19]:
e = np.random.randint(0, 5, size=(2, 4))
e

array([[4, 0, 2, 0],
       [2, 1, 0, 2]])

# dtype

In [20]:
a = np.array([0, 1, 2, 3])
print(a)
a.dtype

[0 1 2 3]


dtype('int64')

In [21]:
b = np.array([0., 1., 2., 3.])
print(b)
b.dtype

[0. 1. 2. 3.]


dtype('float64')

In [22]:
import numpy as np
d = np.array([1.33,2,3.,4])
print(d)
d.dtype

# en numpy, les tableaux sont forcément homogènes car ils sont continus et compactes en mémoire.
# lors de mix numpy prends le dtype le plus utile 

[1.33 2.   3.   4.  ]


dtype('float64')

### Vous devez expliciter le dtype à la création

In [23]:
c1 = np.arange(10, dtype='float64')
print(c1)
c1.dtype

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


dtype('float64')

In [24]:
c2 = np.arange(10, dtype='int16')
print(c2)
c2.dtype

[0 1 2 3 4 5 6 7 8 9]


dtype('int16')


### Le type par défaut est généralement "float64" 

In [25]:
a = np.ones((3, 3), dtype = "int32")
print(a)
a.dtype

# d'ou, la bonne pratique est de spécifier le dtype à chaque fois
# cf sous matlab c'est l'enfer.

[[1 1 1]
 [1 1 1]
 [1 1 1]]


dtype('int32')

### Autres types :

In [26]:
# Complexe :
a = np.array([1+2j, 3+4j, 5+6*1j])
a.dtype

dtype('complex128')

In [27]:
# Booléen
b = np.array([True, False, False, True])
b.dtype

dtype('bool')

In [28]:
# String
c = np.array(['Bonjour', 'Hello', 'Hallo',])
c.dtype             # <--- strings contenant max. 7 lettres

# U7 : unique 7 caractere

dtype('<U7')

# Introduction aux opérations

In [29]:
c = np.arange(10, dtype='float64')
d = np.arange(10, dtype='float64')

print('c : ', c)
print('d : ', d)

c :  [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
d :  [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [30]:
c+1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
c

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [32]:
c+d

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [33]:
c*10+d

array([ 0., 11., 22., 33., 44., 55., 66., 77., 88., 99.])

In [34]:
res = np.log10(c)
print(res)

[      -inf 0.         0.30103    0.47712125 0.60205999 0.69897
 0.77815125 0.84509804 0.90308999 0.95424251]


/home/tkz/.virtualenvs/Py36_formationPythonCrnl2019/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log10
  """Entry point for launching an IPython kernel.


In [35]:
flags = np.isinf(res)
flags

array([ True, False, False, False, False, False, False, False, False,
       False])

In [36]:
np.inf

inf

In [37]:
-np.inf

-inf

In [38]:
np.nan #Not A Number

nan

In [39]:
np.nan + 5

nan

In [40]:
a = np.arange(9)
print(a)
flags = (a>5)
flags

[0 1 2 3 4 5 6 7 8]


array([False, False, False, False, False, False,  True,  True,  True])

In [41]:
a = np.arange(9)
print(a)
flags = (a>2) & (a<=6)
flags



[0 1 2 3 4 5 6 7 8]


array([False, False, False,  True,  True,  True,  True, False, False])

In [42]:
a = np.arange(9)
print(a)
flags = (a>2) | (a<=6)
flags


[0 1 2 3 4 5 6 7 8]


array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [43]:
flags2 = ~flags
flags2

array([False, False, False, False, False, False, False, False, False])